run:
  tests: true
  skip-dirs:
    - execution/contracts

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - unused
    - errcheck
    - revive
    - structcheck
    - typecheck

issues:
  exclude-use-default: false
