// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccessRulesColumns holds the columns for the "access_rules" table.
	AccessRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "role", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AccessRulesTable holds the schema information for the "access_rules" table.
	AccessRulesTable = &schema.Table{
		Name:       "access_rules",
		Columns:    AccessRulesColumns,
		PrimaryKey: []*schema.Column{AccessRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accessrule_type_value",
				Unique:  true,
				Columns: []*schema.Column{AccessRulesColumns[1], AccessRulesColumns[2]},
			},
		},
	}
	// WorkspacesColumns holds the columns for the "workspaces" table.
	WorkspacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "repo", Type: field.TypeString},
		{Name: "owner", Type: field.TypeString},
		{Name: "ref", Type: field.TypeString},
		{Name: "desired_state", Type: field.TypeString},
		{Name: "actual_state", Type: field.TypeString},
		{Name: "execution_profile", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WorkspacesTable holds the schema information for the "workspaces" table.
	WorkspacesTable = &schema.Table{
		Name:       "workspaces",
		Columns:    WorkspacesColumns,
		PrimaryKey: []*schema.Column{WorkspacesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccessRulesTable,
		WorkspacesTable,
	}
)

func init() {
}
