// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/UtopikCode/quickspaces-control-plane/ent/accessrule"
	"github.com/google/uuid"
)

// AccessRuleCreate is the builder for creating a AccessRule entity.
type AccessRuleCreate struct {
	config
	mutation *AccessRuleMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *AccessRuleCreate) SetType(v string) *AccessRuleCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *AccessRuleCreate) SetValue(v string) *AccessRuleCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *AccessRuleCreate) SetRole(v string) *AccessRuleCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccessRuleCreate) SetCreatedAt(v time.Time) *AccessRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccessRuleCreate) SetNillableCreatedAt(v *time.Time) *AccessRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccessRuleCreate) SetID(v uuid.UUID) *AccessRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccessRuleCreate) SetNillableID(v *uuid.UUID) *AccessRuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AccessRuleMutation object of the builder.
func (_c *AccessRuleCreate) Mutation() *AccessRuleMutation {
	return _c.mutation
}

// Save creates the AccessRule in the database.
func (_c *AccessRuleCreate) Save(ctx context.Context) (*AccessRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessRuleCreate) SaveX(ctx context.Context) *AccessRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accessrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := accessrule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessRuleCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "AccessRule.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := accessrule.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AccessRule.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "AccessRule.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := accessrule.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "AccessRule.value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "AccessRule.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := accessrule.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AccessRule.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessRule.created_at"`)}
	}
	return nil
}

func (_c *AccessRuleCreate) sqlSave(ctx context.Context) (*AccessRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessRuleCreate) createSpec() (*AccessRule, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accessrule.Table, sqlgraph.NewFieldSpec(accessrule.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(accessrule.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(accessrule.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(accessrule.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accessrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AccessRuleCreateBulk is the builder for creating many AccessRule entities in bulk.
type AccessRuleCreateBulk struct {
	config
	err      error
	builders []*AccessRuleCreate
}

// Save creates the AccessRule entities in the database.
func (_c *AccessRuleCreateBulk) Save(ctx context.Context) ([]*AccessRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessRuleCreateBulk) SaveX(ctx context.Context) []*AccessRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
