// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/UtopikCode/quickspaces-control-plane/ent/accessrule"
	"github.com/UtopikCode/quickspaces-control-plane/ent/predicate"
)

// AccessRuleUpdate is the builder for updating AccessRule entities.
type AccessRuleUpdate struct {
	config
	hooks    []Hook
	mutation *AccessRuleMutation
}

// Where appends a list predicates to the AccessRuleUpdate builder.
func (_u *AccessRuleUpdate) Where(ps ...predicate.AccessRule) *AccessRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *AccessRuleUpdate) SetType(v string) *AccessRuleUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AccessRuleUpdate) SetNillableType(v *string) *AccessRuleUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *AccessRuleUpdate) SetValue(v string) *AccessRuleUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *AccessRuleUpdate) SetNillableValue(v *string) *AccessRuleUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *AccessRuleUpdate) SetRole(v string) *AccessRuleUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AccessRuleUpdate) SetNillableRole(v *string) *AccessRuleUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AccessRuleUpdate) SetCreatedAt(v time.Time) *AccessRuleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AccessRuleUpdate) SetNillableCreatedAt(v *time.Time) *AccessRuleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AccessRuleMutation object of the builder.
func (_u *AccessRuleUpdate) Mutation() *AccessRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessRuleUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := accessrule.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AccessRule.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := accessrule.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "AccessRule.value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := accessrule.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AccessRule.role": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessrule.Table, accessrule.Columns, sqlgraph.NewFieldSpec(accessrule.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(accessrule.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(accessrule.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(accessrule.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(accessrule.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessRuleUpdateOne is the builder for updating a single AccessRule entity.
type AccessRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessRuleMutation
}

// SetType sets the "type" field.
func (_u *AccessRuleUpdateOne) SetType(v string) *AccessRuleUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AccessRuleUpdateOne) SetNillableType(v *string) *AccessRuleUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *AccessRuleUpdateOne) SetValue(v string) *AccessRuleUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *AccessRuleUpdateOne) SetNillableValue(v *string) *AccessRuleUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *AccessRuleUpdateOne) SetRole(v string) *AccessRuleUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AccessRuleUpdateOne) SetNillableRole(v *string) *AccessRuleUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AccessRuleUpdateOne) SetCreatedAt(v time.Time) *AccessRuleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AccessRuleUpdateOne) SetNillableCreatedAt(v *time.Time) *AccessRuleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AccessRuleMutation object of the builder.
func (_u *AccessRuleUpdateOne) Mutation() *AccessRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccessRuleUpdate builder.
func (_u *AccessRuleUpdateOne) Where(ps ...predicate.AccessRule) *AccessRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessRuleUpdateOne) Select(field string, fields ...string) *AccessRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessRule entity.
func (_u *AccessRuleUpdateOne) Save(ctx context.Context) (*AccessRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessRuleUpdateOne) SaveX(ctx context.Context) *AccessRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessRuleUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := accessrule.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AccessRule.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := accessrule.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "AccessRule.value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := accessrule.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AccessRule.role": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessRuleUpdateOne) sqlSave(ctx context.Context) (_node *AccessRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessrule.Table, accessrule.Columns, sqlgraph.NewFieldSpec(accessrule.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessrule.FieldID)
		for _, f := range fields {
			if !accessrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accessrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(accessrule.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(accessrule.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(accessrule.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(accessrule.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &AccessRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
