// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"time"

	"github.com/UtopikCode/quickspaces-control-plane/ent/accessrule"
	"github.com/UtopikCode/quickspaces-control-plane/ent/schema"
	"github.com/UtopikCode/quickspaces-control-plane/ent/workspace"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accessruleFields := schema.AccessRule{}.Fields()
	_ = accessruleFields
	// accessruleDescType is the schema descriptor for type field.
	accessruleDescType := accessruleFields[1].Descriptor()
	// accessrule.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	accessrule.TypeValidator = accessruleDescType.Validators[0].(func(string) error)
	// accessruleDescValue is the schema descriptor for value field.
	accessruleDescValue := accessruleFields[2].Descriptor()
	// accessrule.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	accessrule.ValueValidator = accessruleDescValue.Validators[0].(func(string) error)
	// accessruleDescRole is the schema descriptor for role field.
	accessruleDescRole := accessruleFields[3].Descriptor()
	// accessrule.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	accessrule.RoleValidator = accessruleDescRole.Validators[0].(func(string) error)
	// accessruleDescCreatedAt is the schema descriptor for created_at field.
	accessruleDescCreatedAt := accessruleFields[4].Descriptor()
	// accessrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	accessrule.DefaultCreatedAt = accessruleDescCreatedAt.Default.(func() time.Time)
	// accessruleDescID is the schema descriptor for id field.
	accessruleDescID := accessruleFields[0].Descriptor()
	// accessrule.DefaultID holds the default value on creation for the id field.
	accessrule.DefaultID = accessruleDescID.Default.(func() uuid.UUID)
	workspaceFields := schema.Workspace{}.Fields()
	_ = workspaceFields
	// workspaceDescRepo is the schema descriptor for repo field.
	workspaceDescRepo := workspaceFields[1].Descriptor()
	// workspace.RepoValidator is a validator for the "repo" field. It is called by the builders before save.
	workspace.RepoValidator = workspaceDescRepo.Validators[0].(func(string) error)
	// workspaceDescOwner is the schema descriptor for owner field.
	workspaceDescOwner := workspaceFields[2].Descriptor()
	// workspace.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	workspace.OwnerValidator = workspaceDescOwner.Validators[0].(func(string) error)
	// workspaceDescRef is the schema descriptor for ref field.
	workspaceDescRef := workspaceFields[3].Descriptor()
	// workspace.RefValidator is a validator for the "ref" field. It is called by the builders before save.
	workspace.RefValidator = workspaceDescRef.Validators[0].(func(string) error)
	// workspaceDescDesiredState is the schema descriptor for desired_state field.
	workspaceDescDesiredState := workspaceFields[4].Descriptor()
	// workspace.DesiredStateValidator is a validator for the "desired_state" field. It is called by the builders before save.
	workspace.DesiredStateValidator = workspaceDescDesiredState.Validators[0].(func(string) error)
	// workspaceDescActualState is the schema descriptor for actual_state field.
	workspaceDescActualState := workspaceFields[5].Descriptor()
	// workspace.ActualStateValidator is a validator for the "actual_state" field. It is called by the builders before save.
	workspace.ActualStateValidator = workspaceDescActualState.Validators[0].(func(string) error)
	// workspaceDescExecutionProfile is the schema descriptor for execution_profile field.
	workspaceDescExecutionProfile := workspaceFields[6].Descriptor()
	// workspace.DefaultExecutionProfile holds the default value on creation for the execution_profile field.
	workspace.DefaultExecutionProfile = workspaceDescExecutionProfile.Default.(json.RawMessage)
	// workspaceDescCreatedAt is the schema descriptor for created_at field.
	workspaceDescCreatedAt := workspaceFields[7].Descriptor()
	// workspace.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspace.DefaultCreatedAt = workspaceDescCreatedAt.Default.(func() time.Time)
	// workspaceDescUpdatedAt is the schema descriptor for updated_at field.
	workspaceDescUpdatedAt := workspaceFields[8].Descriptor()
	// workspace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspace.DefaultUpdatedAt = workspaceDescUpdatedAt.Default.(func() time.Time)
	// workspace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspace.UpdateDefaultUpdatedAt = workspaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspaceDescID is the schema descriptor for id field.
	workspaceDescID := workspaceFields[0].Descriptor()
	// workspace.IDValidator is a validator for the "id" field. It is called by the builders before save.
	workspace.IDValidator = workspaceDescID.Validators[0].(func(string) error)
}
