// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/UtopikCode/quickspaces-control-plane/ent/workspace"
)

// WorkspaceCreate is the builder for creating a Workspace entity.
type WorkspaceCreate struct {
	config
	mutation *WorkspaceMutation
	hooks    []Hook
}

// SetRepo sets the "repo" field.
func (_c *WorkspaceCreate) SetRepo(v string) *WorkspaceCreate {
	_c.mutation.SetRepo(v)
	return _c
}

// SetOwner sets the "owner" field.
func (_c *WorkspaceCreate) SetOwner(v string) *WorkspaceCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetRef sets the "ref" field.
func (_c *WorkspaceCreate) SetRef(v string) *WorkspaceCreate {
	_c.mutation.SetRef(v)
	return _c
}

// SetDesiredState sets the "desired_state" field.
func (_c *WorkspaceCreate) SetDesiredState(v string) *WorkspaceCreate {
	_c.mutation.SetDesiredState(v)
	return _c
}

// SetActualState sets the "actual_state" field.
func (_c *WorkspaceCreate) SetActualState(v string) *WorkspaceCreate {
	_c.mutation.SetActualState(v)
	return _c
}

// SetExecutionProfile sets the "execution_profile" field.
func (_c *WorkspaceCreate) SetExecutionProfile(v json.RawMessage) *WorkspaceCreate {
	_c.mutation.SetExecutionProfile(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceCreate) SetCreatedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkspaceCreate) SetUpdatedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableUpdatedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkspaceCreate) SetID(v string) *WorkspaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_c *WorkspaceCreate) Mutation() *WorkspaceMutation {
	return _c.mutation
}

// Save creates the Workspace in the database.
func (_c *WorkspaceCreate) Save(ctx context.Context) (*Workspace, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceCreate) SaveX(ctx context.Context) *Workspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceCreate) defaults() {
	if _, ok := _c.mutation.ExecutionProfile(); !ok {
		v := workspace.DefaultExecutionProfile
		_c.mutation.SetExecutionProfile(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workspace.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := workspace.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceCreate) check() error {
	if _, ok := _c.mutation.Repo(); !ok {
		return &ValidationError{Name: "repo", err: errors.New(`ent: missing required field "Workspace.repo"`)}
	}
	if v, ok := _c.mutation.Repo(); ok {
		if err := workspace.RepoValidator(v); err != nil {
			return &ValidationError{Name: "repo", err: fmt.Errorf(`ent: validator failed for field "Workspace.repo": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "Workspace.owner"`)}
	}
	if v, ok := _c.mutation.Owner(); ok {
		if err := workspace.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Workspace.owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ref(); !ok {
		return &ValidationError{Name: "ref", err: errors.New(`ent: missing required field "Workspace.ref"`)}
	}
	if v, ok := _c.mutation.Ref(); ok {
		if err := workspace.RefValidator(v); err != nil {
			return &ValidationError{Name: "ref", err: fmt.Errorf(`ent: validator failed for field "Workspace.ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DesiredState(); !ok {
		return &ValidationError{Name: "desired_state", err: errors.New(`ent: missing required field "Workspace.desired_state"`)}
	}
	if v, ok := _c.mutation.DesiredState(); ok {
		if err := workspace.DesiredStateValidator(v); err != nil {
			return &ValidationError{Name: "desired_state", err: fmt.Errorf(`ent: validator failed for field "Workspace.desired_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActualState(); !ok {
		return &ValidationError{Name: "actual_state", err: errors.New(`ent: missing required field "Workspace.actual_state"`)}
	}
	if v, ok := _c.mutation.ActualState(); ok {
		if err := workspace.ActualStateValidator(v); err != nil {
			return &ValidationError{Name: "actual_state", err: fmt.Errorf(`ent: validator failed for field "Workspace.actual_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionProfile(); !ok {
		return &ValidationError{Name: "execution_profile", err: errors.New(`ent: missing required field "Workspace.execution_profile"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Workspace.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Workspace.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := workspace.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Workspace.id": %w`, err)}
		}
	}
	return nil
}

func (_c *WorkspaceCreate) sqlSave(ctx context.Context) (*Workspace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Workspace.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceCreate) createSpec() (*Workspace, *sqlgraph.CreateSpec) {
	var (
		_node = &Workspace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspace.Table, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Repo(); ok {
		_spec.SetField(workspace.FieldRepo, field.TypeString, value)
		_node.Repo = value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(workspace.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.Ref(); ok {
		_spec.SetField(workspace.FieldRef, field.TypeString, value)
		_node.Ref = value
	}
	if value, ok := _c.mutation.DesiredState(); ok {
		_spec.SetField(workspace.FieldDesiredState, field.TypeString, value)
		_node.DesiredState = value
	}
	if value, ok := _c.mutation.ActualState(); ok {
		_spec.SetField(workspace.FieldActualState, field.TypeString, value)
		_node.ActualState = value
	}
	if value, ok := _c.mutation.ExecutionProfile(); ok {
		_spec.SetField(workspace.FieldExecutionProfile, field.TypeJSON, value)
		_node.ExecutionProfile = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// WorkspaceCreateBulk is the builder for creating many Workspace entities in bulk.
type WorkspaceCreateBulk struct {
	config
	err      error
	builders []*WorkspaceCreate
}

// Save creates the Workspace entities in the database.
func (_c *WorkspaceCreateBulk) Save(ctx context.Context) ([]*Workspace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Workspace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceCreateBulk) SaveX(ctx context.Context) []*Workspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
