// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/UtopikCode/quickspaces-control-plane/ent/predicate"
	"github.com/UtopikCode/quickspaces-control-plane/ent/workspace"
)

// WorkspaceUpdate is the builder for updating Workspace entities.
type WorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (_u *WorkspaceUpdate) Where(ps ...predicate.Workspace) *WorkspaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRepo sets the "repo" field.
func (_u *WorkspaceUpdate) SetRepo(v string) *WorkspaceUpdate {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableRepo(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// SetOwner sets the "owner" field.
func (_u *WorkspaceUpdate) SetOwner(v string) *WorkspaceUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableOwner(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetRef sets the "ref" field.
func (_u *WorkspaceUpdate) SetRef(v string) *WorkspaceUpdate {
	_u.mutation.SetRef(v)
	return _u
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableRef(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetRef(*v)
	}
	return _u
}

// SetDesiredState sets the "desired_state" field.
func (_u *WorkspaceUpdate) SetDesiredState(v string) *WorkspaceUpdate {
	_u.mutation.SetDesiredState(v)
	return _u
}

// SetNillableDesiredState sets the "desired_state" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableDesiredState(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetDesiredState(*v)
	}
	return _u
}

// SetActualState sets the "actual_state" field.
func (_u *WorkspaceUpdate) SetActualState(v string) *WorkspaceUpdate {
	_u.mutation.SetActualState(v)
	return _u
}

// SetNillableActualState sets the "actual_state" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableActualState(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetActualState(*v)
	}
	return _u
}

// SetExecutionProfile sets the "execution_profile" field.
func (_u *WorkspaceUpdate) SetExecutionProfile(v json.RawMessage) *WorkspaceUpdate {
	_u.mutation.SetExecutionProfile(v)
	return _u
}

// AppendExecutionProfile appends value to the "execution_profile" field.
func (_u *WorkspaceUpdate) AppendExecutionProfile(v json.RawMessage) *WorkspaceUpdate {
	_u.mutation.AppendExecutionProfile(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceUpdate) SetCreatedAt(v time.Time) *WorkspaceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableCreatedAt(v *time.Time) *WorkspaceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceUpdate) SetUpdatedAt(v time.Time) *WorkspaceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_u *WorkspaceUpdate) Mutation() *WorkspaceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceUpdate) check() error {
	if v, ok := _u.mutation.Repo(); ok {
		if err := workspace.RepoValidator(v); err != nil {
			return &ValidationError{Name: "repo", err: fmt.Errorf(`ent: validator failed for field "Workspace.repo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Owner(); ok {
		if err := workspace.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Workspace.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ref(); ok {
		if err := workspace.RefValidator(v); err != nil {
			return &ValidationError{Name: "ref", err: fmt.Errorf(`ent: validator failed for field "Workspace.ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DesiredState(); ok {
		if err := workspace.DesiredStateValidator(v); err != nil {
			return &ValidationError{Name: "desired_state", err: fmt.Errorf(`ent: validator failed for field "Workspace.desired_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualState(); ok {
		if err := workspace.ActualStateValidator(v); err != nil {
			return &ValidationError{Name: "actual_state", err: fmt.Errorf(`ent: validator failed for field "Workspace.actual_state": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(workspace.FieldRepo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(workspace.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ref(); ok {
		_spec.SetField(workspace.FieldRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.DesiredState(); ok {
		_spec.SetField(workspace.FieldDesiredState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualState(); ok {
		_spec.SetField(workspace.FieldActualState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionProfile(); ok {
		_spec.SetField(workspace.FieldExecutionProfile, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExecutionProfile(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workspace.FieldExecutionProfile, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceUpdateOne is the builder for updating a single Workspace entity.
type WorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMutation
}

// SetRepo sets the "repo" field.
func (_u *WorkspaceUpdateOne) SetRepo(v string) *WorkspaceUpdateOne {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableRepo(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// SetOwner sets the "owner" field.
func (_u *WorkspaceUpdateOne) SetOwner(v string) *WorkspaceUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableOwner(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetRef sets the "ref" field.
func (_u *WorkspaceUpdateOne) SetRef(v string) *WorkspaceUpdateOne {
	_u.mutation.SetRef(v)
	return _u
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableRef(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetRef(*v)
	}
	return _u
}

// SetDesiredState sets the "desired_state" field.
func (_u *WorkspaceUpdateOne) SetDesiredState(v string) *WorkspaceUpdateOne {
	_u.mutation.SetDesiredState(v)
	return _u
}

// SetNillableDesiredState sets the "desired_state" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableDesiredState(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetDesiredState(*v)
	}
	return _u
}

// SetActualState sets the "actual_state" field.
func (_u *WorkspaceUpdateOne) SetActualState(v string) *WorkspaceUpdateOne {
	_u.mutation.SetActualState(v)
	return _u
}

// SetNillableActualState sets the "actual_state" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableActualState(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetActualState(*v)
	}
	return _u
}

// SetExecutionProfile sets the "execution_profile" field.
func (_u *WorkspaceUpdateOne) SetExecutionProfile(v json.RawMessage) *WorkspaceUpdateOne {
	_u.mutation.SetExecutionProfile(v)
	return _u
}

// AppendExecutionProfile appends value to the "execution_profile" field.
func (_u *WorkspaceUpdateOne) AppendExecutionProfile(v json.RawMessage) *WorkspaceUpdateOne {
	_u.mutation.AppendExecutionProfile(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceUpdateOne) SetCreatedAt(v time.Time) *WorkspaceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableCreatedAt(v *time.Time) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceUpdateOne) SetUpdatedAt(v time.Time) *WorkspaceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_u *WorkspaceUpdateOne) Mutation() *WorkspaceMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (_u *WorkspaceUpdateOne) Where(ps ...predicate.Workspace) *WorkspaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceUpdateOne) Select(field string, fields ...string) *WorkspaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Workspace entity.
func (_u *WorkspaceUpdateOne) Save(ctx context.Context) (*Workspace, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceUpdateOne) SaveX(ctx context.Context) *Workspace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceUpdateOne) check() error {
	if v, ok := _u.mutation.Repo(); ok {
		if err := workspace.RepoValidator(v); err != nil {
			return &ValidationError{Name: "repo", err: fmt.Errorf(`ent: validator failed for field "Workspace.repo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Owner(); ok {
		if err := workspace.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Workspace.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ref(); ok {
		if err := workspace.RefValidator(v); err != nil {
			return &ValidationError{Name: "ref", err: fmt.Errorf(`ent: validator failed for field "Workspace.ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DesiredState(); ok {
		if err := workspace.DesiredStateValidator(v); err != nil {
			return &ValidationError{Name: "desired_state", err: fmt.Errorf(`ent: validator failed for field "Workspace.desired_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualState(); ok {
		if err := workspace.ActualStateValidator(v); err != nil {
			return &ValidationError{Name: "actual_state", err: fmt.Errorf(`ent: validator failed for field "Workspace.actual_state": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *Workspace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspace.FieldID)
		for _, f := range fields {
			if !workspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(workspace.FieldRepo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(workspace.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ref(); ok {
		_spec.SetField(workspace.FieldRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.DesiredState(); ok {
		_spec.SetField(workspace.FieldDesiredState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualState(); ok {
		_spec.SetField(workspace.FieldActualState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionProfile(); ok {
		_spec.SetField(workspace.FieldExecutionProfile, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExecutionProfile(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workspace.FieldExecutionProfile, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Workspace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
