// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/UtopikCode/quickspaces-control-plane/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldID, id))
}

// Repo applies equality check predicate on the "repo" field. It's identical to RepoEQ.
func Repo(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRepo, v))
}

// Owner applies equality check predicate on the "owner" field. It's identical to OwnerEQ.
func Owner(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldOwner, v))
}

// Ref applies equality check predicate on the "ref" field. It's identical to RefEQ.
func Ref(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRef, v))
}

// DesiredState applies equality check predicate on the "desired_state" field. It's identical to DesiredStateEQ.
func DesiredState(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldDesiredState, v))
}

// ActualState applies equality check predicate on the "actual_state" field. It's identical to ActualStateEQ.
func ActualState(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldActualState, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldUpdatedAt, v))
}

// RepoEQ applies the EQ predicate on the "repo" field.
func RepoEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRepo, v))
}

// RepoNEQ applies the NEQ predicate on the "repo" field.
func RepoNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldRepo, v))
}

// RepoIn applies the In predicate on the "repo" field.
func RepoIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldRepo, vs...))
}

// RepoNotIn applies the NotIn predicate on the "repo" field.
func RepoNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldRepo, vs...))
}

// RepoGT applies the GT predicate on the "repo" field.
func RepoGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldRepo, v))
}

// RepoGTE applies the GTE predicate on the "repo" field.
func RepoGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldRepo, v))
}

// RepoLT applies the LT predicate on the "repo" field.
func RepoLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldRepo, v))
}

// RepoLTE applies the LTE predicate on the "repo" field.
func RepoLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldRepo, v))
}

// RepoContains applies the Contains predicate on the "repo" field.
func RepoContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldRepo, v))
}

// RepoHasPrefix applies the HasPrefix predicate on the "repo" field.
func RepoHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldRepo, v))
}

// RepoHasSuffix applies the HasSuffix predicate on the "repo" field.
func RepoHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldRepo, v))
}

// RepoEqualFold applies the EqualFold predicate on the "repo" field.
func RepoEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldRepo, v))
}

// RepoContainsFold applies the ContainsFold predicate on the "repo" field.
func RepoContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldRepo, v))
}

// OwnerEQ applies the EQ predicate on the "owner" field.
func OwnerEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldOwner, v))
}

// OwnerNEQ applies the NEQ predicate on the "owner" field.
func OwnerNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldOwner, v))
}

// OwnerIn applies the In predicate on the "owner" field.
func OwnerIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldOwner, vs...))
}

// OwnerNotIn applies the NotIn predicate on the "owner" field.
func OwnerNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldOwner, vs...))
}

// OwnerGT applies the GT predicate on the "owner" field.
func OwnerGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldOwner, v))
}

// OwnerGTE applies the GTE predicate on the "owner" field.
func OwnerGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldOwner, v))
}

// OwnerLT applies the LT predicate on the "owner" field.
func OwnerLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldOwner, v))
}

// OwnerLTE applies the LTE predicate on the "owner" field.
func OwnerLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldOwner, v))
}

// OwnerContains applies the Contains predicate on the "owner" field.
func OwnerContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldOwner, v))
}

// OwnerHasPrefix applies the HasPrefix predicate on the "owner" field.
func OwnerHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldOwner, v))
}

// OwnerHasSuffix applies the HasSuffix predicate on the "owner" field.
func OwnerHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldOwner, v))
}

// OwnerEqualFold applies the EqualFold predicate on the "owner" field.
func OwnerEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldOwner, v))
}

// OwnerContainsFold applies the ContainsFold predicate on the "owner" field.
func OwnerContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldOwner, v))
}

// RefEQ applies the EQ predicate on the "ref" field.
func RefEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldRef, v))
}

// RefNEQ applies the NEQ predicate on the "ref" field.
func RefNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldRef, v))
}

// RefIn applies the In predicate on the "ref" field.
func RefIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldRef, vs...))
}

// RefNotIn applies the NotIn predicate on the "ref" field.
func RefNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldRef, vs...))
}

// RefGT applies the GT predicate on the "ref" field.
func RefGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldRef, v))
}

// RefGTE applies the GTE predicate on the "ref" field.
func RefGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldRef, v))
}

// RefLT applies the LT predicate on the "ref" field.
func RefLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldRef, v))
}

// RefLTE applies the LTE predicate on the "ref" field.
func RefLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldRef, v))
}

// RefContains applies the Contains predicate on the "ref" field.
func RefContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldRef, v))
}

// RefHasPrefix applies the HasPrefix predicate on the "ref" field.
func RefHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldRef, v))
}

// RefHasSuffix applies the HasSuffix predicate on the "ref" field.
func RefHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldRef, v))
}

// RefEqualFold applies the EqualFold predicate on the "ref" field.
func RefEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldRef, v))
}

// RefContainsFold applies the ContainsFold predicate on the "ref" field.
func RefContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldRef, v))
}

// DesiredStateEQ applies the EQ predicate on the "desired_state" field.
func DesiredStateEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldDesiredState, v))
}

// DesiredStateNEQ applies the NEQ predicate on the "desired_state" field.
func DesiredStateNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldDesiredState, v))
}

// DesiredStateIn applies the In predicate on the "desired_state" field.
func DesiredStateIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldDesiredState, vs...))
}

// DesiredStateNotIn applies the NotIn predicate on the "desired_state" field.
func DesiredStateNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldDesiredState, vs...))
}

// DesiredStateGT applies the GT predicate on the "desired_state" field.
func DesiredStateGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldDesiredState, v))
}

// DesiredStateGTE applies the GTE predicate on the "desired_state" field.
func DesiredStateGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldDesiredState, v))
}

// DesiredStateLT applies the LT predicate on the "desired_state" field.
func DesiredStateLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldDesiredState, v))
}

// DesiredStateLTE applies the LTE predicate on the "desired_state" field.
func DesiredStateLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldDesiredState, v))
}

// DesiredStateContains applies the Contains predicate on the "desired_state" field.
func DesiredStateContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldDesiredState, v))
}

// DesiredStateHasPrefix applies the HasPrefix predicate on the "desired_state" field.
func DesiredStateHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldDesiredState, v))
}

// DesiredStateHasSuffix applies the HasSuffix predicate on the "desired_state" field.
func DesiredStateHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldDesiredState, v))
}

// DesiredStateEqualFold applies the EqualFold predicate on the "desired_state" field.
func DesiredStateEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldDesiredState, v))
}

// DesiredStateContainsFold applies the ContainsFold predicate on the "desired_state" field.
func DesiredStateContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldDesiredState, v))
}

// ActualStateEQ applies the EQ predicate on the "actual_state" field.
func ActualStateEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldActualState, v))
}

// ActualStateNEQ applies the NEQ predicate on the "actual_state" field.
func ActualStateNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldActualState, v))
}

// ActualStateIn applies the In predicate on the "actual_state" field.
func ActualStateIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldActualState, vs...))
}

// ActualStateNotIn applies the NotIn predicate on the "actual_state" field.
func ActualStateNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldActualState, vs...))
}

// ActualStateGT applies the GT predicate on the "actual_state" field.
func ActualStateGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldActualState, v))
}

// ActualStateGTE applies the GTE predicate on the "actual_state" field.
func ActualStateGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldActualState, v))
}

// ActualStateLT applies the LT predicate on the "actual_state" field.
func ActualStateLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldActualState, v))
}

// ActualStateLTE applies the LTE predicate on the "actual_state" field.
func ActualStateLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldActualState, v))
}

// ActualStateContains applies the Contains predicate on the "actual_state" field.
func ActualStateContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldActualState, v))
}

// ActualStateHasPrefix applies the HasPrefix predicate on the "actual_state" field.
func ActualStateHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldActualState, v))
}

// ActualStateHasSuffix applies the HasSuffix predicate on the "actual_state" field.
func ActualStateHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldActualState, v))
}

// ActualStateEqualFold applies the EqualFold predicate on the "actual_state" field.
func ActualStateEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldActualState, v))
}

// ActualStateContainsFold applies the ContainsFold predicate on the "actual_state" field.
func ActualStateContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldActualState, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.NotPredicates(p))
}
