// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"encoding/json"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the workspace type in the database.
	Label = "workspace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepo holds the string denoting the repo field in the database.
	FieldRepo = "repo"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldRef holds the string denoting the ref field in the database.
	FieldRef = "ref"
	// FieldDesiredState holds the string denoting the desired_state field in the database.
	FieldDesiredState = "desired_state"
	// FieldActualState holds the string denoting the actual_state field in the database.
	FieldActualState = "actual_state"
	// FieldExecutionProfile holds the string denoting the execution_profile field in the database.
	FieldExecutionProfile = "execution_profile"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the workspace in the database.
	Table = "workspaces"
)

// Columns holds all SQL columns for workspace fields.
var Columns = []string{
	FieldID,
	FieldRepo,
	FieldOwner,
	FieldRef,
	FieldDesiredState,
	FieldActualState,
	FieldExecutionProfile,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RepoValidator is a validator for the "repo" field. It is called by the builders before save.
	RepoValidator func(string) error
	// OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	OwnerValidator func(string) error
	// RefValidator is a validator for the "ref" field. It is called by the builders before save.
	RefValidator func(string) error
	// DesiredStateValidator is a validator for the "desired_state" field. It is called by the builders before save.
	DesiredStateValidator func(string) error
	// ActualStateValidator is a validator for the "actual_state" field. It is called by the builders before save.
	ActualStateValidator func(string) error
	// DefaultExecutionProfile holds the default value on creation for the "execution_profile" field.
	DefaultExecutionProfile json.RawMessage
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Workspace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepo orders the results by the repo field.
func ByRepo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepo, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByRef orders the results by the ref field.
func ByRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRef, opts...).ToFunc()
}

// ByDesiredState orders the results by the desired_state field.
func ByDesiredState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesiredState, opts...).ToFunc()
}

// ByActualState orders the results by the actual_state field.
func ByActualState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualState, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
